### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by qoomon** [dstd/micSwitch#2]
First thanks for this great app.
It would be great if you could adjust menu icon behaviour to something like
* **red** mic icon, if mic is enabled
* **grey** mic icon ,if mic is disabled

or even better
* **red** mic icon, if mic is enabled and an application is activly using the mic like [microsnitch](https://www.obdev.at/products/microsnitch/index.html)
* **white** mic icon, if mic is enabled and no application is using it
* **grey** mic icon ,if mic is disabled

**Comment by qoomon** [comment]
Mic usage detection should work this way -> https://stackoverflow.com/a/40418961/5376635

**Comment by dstd** [comment]
Yeah, it's been a while 🙈 But for the strong and patient ones – https://github.com/dstd/micSwitch/releases/tag/1.2

**Comment by qoomon** [comment]
Thanks
