### ISSUE TITLE
Red icon in v1.2

### ISSUE THREAD

**Issue by coreequip** [dstd/micSwitch#3]
Hi Denis,

thanks for this nice tool.

I have just installed the v1.2 on macOS Ventura and I see a red microphone (not like the one in your screenshot).

**Comment by dstd** [comment]
Red icon means that some application is capturing the audio. At least it meant to be that way. Maybe there is some breaking change in Ventura. Unfortunately I can't test/debug it in the near future.

Also on Monterey (and probably later versions too) bluetooth connected devices can't be managed by API used by this application, and I haven't yet found any workaround for this too.

I'm sorry.
